#!/bin/bash
# /etc/init.d/fermtemp

### BEGIN INIT INFO
# Provides:          fermtemp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

COMMAND="/home/ken/.virtualenvs/brewtemp/bin/python /opt/fermtemp/fermTempService.py"


case "$1" in
    start)
        echo "Starting fermtemp"
        $COMMAND
        echo "Fermtemp started"
        ;;
    stop)
        echo "Stopping fermtemp"
        kill -9 $(ps aux | grep fermtemp | grep -v grep | awk '{print $2}')
        echo "Fermtemp stopped"
        ;;
    status)
        line=$(ps aux | grep fermtemp | grep -v grep)
        if [ -z "$line" ]; then
            echo "Fermtemp is running"
        else
            echo "Fermtemp is stopped"
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/fermtemp start|stop|status"
        exit 1
        ;;
esac

exit 0
