#!/bin/bash
# /etc/init.d/fermtemp

### BEGIN INIT INFO
# Provides:          fermtemp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO

COMMAND="/home/ken/.virtualenvs/pi-mon/bin/python /opt/fermtemp/fermTempService.py"


case "$1" in 
    start)
        echo "Starting fermtemp"
        $COMMAND
        ;;
    stop)
        echo "Stopping fermtemp"
        killall fermTempService.py
        ;;
    *)
        echo "Usage: /etc/init.d/fermtemp start|stop"
        exit 1
        ;;
esac

exit 0